CREATE TABLE IF NOT EXISTS rail_defects (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    payload JSON NOT NULL
);

CREATE TABLE IF NOT EXISTS rail_slots (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    payload JSON NOT NULL
);

CREATE TABLE IF NOT EXISTS rail_weekly_schedule (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    payload JSON NOT NULL
);

CREATE TABLE IF NOT EXISTS rail_monthly_schedule (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    payload JSON NOT NULL
);

CREATE TABLE IF NOT EXISTS rail_unscheduled_weekly (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    payload JSON NOT NULL
);

CREATE TABLE IF NOT EXISTS rail_unscheduled_monthly (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    payload JSON NOT NULL
);






